export const CATEGORIES = [
  { value: 'mixte',        label: '🛍️ Boutique Mixte / Généraliste' },
  { value: 'smartphones',  label: '📱 Téléphone / Smartphone' },
  { value: 'informatique', label: '💻 Informatique' },
  { value: 'tv-electro',   label: '📺 TV & Électroménager' },
  { value: 'mode',         label: '👗 Mode & Vêtements' },
  { value: 'maison',       label: '🏠 Maison & Décoration' },
  { value: 'auto-moto',    label: '🚗 Auto & Moto' },
  { value: 'jeux',         label: '🎮 Jeux & Consoles' },
  { value: 'alimentation', label: '🍚 Alimentation & Épicerie' },
  { value: 'beaute',       label: '💄 Beauté & Soins' },
  { value: 'sport',        label: '⚽ Sport & Fitness' },
  { value: 'fournitures',  label: '📚 Fournitures & Bureautique' },
  { value: 'quincaillerie',label: '🧱 Quincaillerie & BTP' },
  { value: 'pieces-rechange',label: '⚙️ Pièces de Rechange' },
  { value: 'bijouterie',   label: '💎 Bijouterie & Horlogerie' },
  { value: 'maraichage',   label: '🥕 Maraîchage & Fruits/Légumes' },
  { value: 'elevage',      label: '🐑 Élevage & Aliments Bétail' },
  { value: 'produits-agricoles', label: '🌾 Produits Agricoles & Intrants' },
  { value: 'solaire-energie', label: '☀️ Solaire & Énergie' },
  { value: 'sante-pharma',  label: '💊 Santé & Pharmacie' },
  { value: 'bebe-enfants',  label: '👶 Bébé & Enfants' },
  { value: 'services',     label: '🛠 Services' },
  { value: 'immo',         label: '🏢 Immobilier & Terrains' },
  { value: 'annonces',     label: '📢 Petites Annonces' },
  { value: 'autre',        label: '📦 Autre' },
]

export const PRODUIT_CATEGORIES = CATEGORIES;
